# ===================================================================
# Spring Boot configuration for the "dev" profile.
#
# This configuration overrides the application.yml file.
#
# ===================================================================

# ===================================================================
# Standard Spring Boot properties.
# Full reference is available at:
# http://docs.spring.io/spring-boot/docs/current/reference/html/common-application-properties.html
# ===================================================================

logging:
  level:
    ROOT: DEBUG
    com.zaggle: DEBUG
    org.hibernate.SQL: DEBUG
    com.zaggle.xpns.organization: DEBUG




spring:
  devtools:
    restart:
      enabled: true
      additional-exclude: static/**,.h2.server.properties
    livereload:
      enabled: false # we use Webpack dev server + BrowserSync for livereload
  jackson:
    serialization:
      indent-output: true
  cloud:
    config:
      #uri: http://
      # name of the config server's property source (file.yml) that we want to use
      name: authentication
      profile: dev
      label: main # toggle to switch to a different version of the configuration as stored in git
      # it can be set to any label, branch or commit of the configuration source Git repository
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:postgresql://admin-authentication.cety3rmbtz1s.ap-south-1.rds.amazonaws.com/admin_authentication
    username: admin_auth
    password: I6vYa7UmG#0v
    hikari:
      poolName: Hikari
      auto-commit: false
  h2:
    console:
      # disable spring boot built-in h2-console since we start it manually with correct configuration
      enabled: false

  elasticsearch:
    uris: http://localhost:9200
  liquibase:
    # Remove 'faker' if you do not want the sample data to be loaded automatically
    contexts: dev
    enabled: false
  messages:
    cache-duration: PT1S # 1 second, see the ISO 8601 standard
  thymeleaf:
    cache: false
  sleuth:
    # https://github.com/spring-projects/spring-framework/issues/27844#issuescomment-1002866885
    # https://github.com/spring-cloud/spring-cloud-sleuth/issues/2094
    async:
      enabled: false
    enabled: false
    sampler:
      probability: 1 # report 100% of traces



server:
  connection-timeout=60000:
  port: 8194
  servlet:
    contextPath: /adminAuthentication

    jpa:
      hibernate:
        ddl-auto: create

# ===================================================================

# ===================================================================

xpns:
  cache: # Cache configuration
    redis: # Redis configuration
      expiration: 3600 # By default objects stay 1 hour (in seconds) in the cache
      server: redis://localhost:6379
      cluster: false
      # server: redis://localhost:6379,redis://localhost:16379,redis://localhost:26379
      # cluster: true
  registry:
    password: admin
      # CORS is disabled by default on microservices, as you should access them through a gateway.
      # If you want to enable it, please uncomment the configuration below.
      # cors:
      #   allowed-origins: "http://localhost:9000,https://localhost:9000"
      #   allowed-methods: "*"
      #   allowed-headers: "*"
    #   exposed-headers: "Authorization,Link,X-Total-Count"
    #   allow-credentials: true
    #   max-age: 1800

  logging:
    use-json-format: false # By default, logs are not in Json format
    logstash: # Forward logs to logstash over a socket, used by LoggingConfiguration
      enabled: false
      host: localhost
      port: 50000
      queue-size: 512
# ===================================================================
# Application specific properties
# Add your own application properties here, see the ApplicationProperties class
# ===================================================================

# application:
